language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
matrix:
  allow_failures:
    - os: osx
script:
  - make fixeof
  - make genquid
  - make debug
  - make test
  - ./bin/quantica_test
  - ./test/dupquid.sh
