language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  allow_failures:
    - os: osx

before_script:
  - git clone https://github.com/akheron/jansson
  - pushd jansson
  - autoreconf -i
  - ./configure
  - make
  - sudo make install
  - popd
  - rm -fr jansson

script:
  - make fixeof
  - make genquid
  - make debug
  - make test
  - ./bin/quantica_test
  - ./test/dupquid.sh
