#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define PROGNAME		"Quantica"
#define INSTANCE_PREFIX	"QUANTZ"
#define VERSION_RELESE	0
#define VERSION_MAJOR	7
#define VERSION_MINOR	42
#define LOGFILE			"quantica.log"
#define BINDATA			"QUBIN_DATA"
#define DEFAULT_PREFIX	"00000000-00c1-a150-0000"

#define CACHE_SLOTS	23
#define DBCACHE_SLOTS	25
#define DBCACHE_DENSITY	75

#define API_PORT	4017
#define LICENSE		"BSD 3-clause"

#endif // CONFIG_H_INCLUDED
